import type { AutomationAction } from "@types-app/automation.types";

export const AUTOMATION_ACTIONS: AutomationAction[] = [
  {
    id: "send_email",
    label: "Send Email",
    description: "Dispatch a branded email to recipients.",
    category: "communication",
    icon: "Mail",
    estimatedDurationMs: 800,
    params: [
      {
        key: "to",
        label: "Recipient Email",
        type: "email",
        required: true,
        placeholder: "user@company.com",
      },
      {
        key: "subject",
        label: "Subject Line",
        type: "text",
        required: true,
        placeholder: "Your onboarding is ready",
      },
      {
        key: "template",
        label: "Email Template",
        type: "select",
        required: false,
        options: ["welcome", "reminder", "approval_request", "rejection", "completion"],
      },
    ],
  },
  {
    id: "generate_doc",
    label: "Generate Document",
    description: "Create a document from a saved template.",
    category: "document",
    icon: "FileText",
    estimatedDurationMs: 1500,
    params: [
      {
        key: "template",
        label: "Document Template",
        type: "select",
        required: true,
        options: ["offer_letter", "nda", "employee_handbook", "policy_doc", "termination_letter"],
      },
      {
        key: "recipient",
        label: "Recipient Full Name",
        type: "text",
        required: true,
        placeholder: "Jane Doe",
      },
      {
        key: "format",
        label: "Output Format",
        type: "select",
        required: true,
        options: ["pdf", "docx"],
      },
    ],
  },
  {
    id: "slack_notify",
    label: "Slack Notification",
    description: "Post an update into a channel or direct message.",
    category: "communication",
    icon: "MessageSquare",
    estimatedDurationMs: 420,
    params: [
      {
        key: "channel",
        label: "Channel or Username",
        type: "text",
        required: true,
        placeholder: "#ops or @alex",
      },
      {
        key: "message",
        label: "Message Body",
        type: "textarea",
        required: true,
        placeholder: "Employee onboarding initiated for...",
      },
      {
        key: "mention_user",
        label: "Mention User",
        type: "text",
        required: false,
        placeholder: "@jane.smith",
      },
    ],
  },
  {
    id: "create_ticket",
    label: "Create IT Ticket",
    description: "Open a helpdesk ticket for provisioning or follow-up.",
    category: "integration",
    icon: "Ticket",
    estimatedDurationMs: 640,
    params: [
      {
        key: "title",
        label: "Ticket Title",
        type: "text",
        required: true,
        placeholder: "Provision laptop for new hire",
      },
      {
        key: "priority",
        label: "Priority Level",
        type: "select",
        required: true,
        options: ["low", "medium", "high", "critical"],
      },
      {
        key: "team",
        label: "Assign To Team",
        type: "select",
        required: true,
        options: ["IT Infrastructure", "Security", "Finance", "HR Operations", "Legal"],
      },
      {
        key: "due_days",
        label: "Due In (days)",
        type: "number",
        required: false,
        placeholder: "3",
      },
    ],
  },
  {
    id: "update_hris",
    label: "Update HRIS Record",
    description: "Sync employee data into the HR system of record.",
    category: "data",
    icon: "Database",
    estimatedDurationMs: 1100,
    params: [
      {
        key: "field",
        label: "Field to Update",
        type: "select",
        required: true,
        options: [
          "employment_status",
          "department",
          "manager",
          "location",
          "salary_band",
          "role_title",
        ],
      },
      {
        key: "value",
        label: "New Value",
        type: "text",
        required: true,
        placeholder: "Active",
      },
      {
        key: "effective_date",
        label: "Effective Date",
        type: "text",
        required: false,
        placeholder: "YYYY-MM-DD",
      },
    ],
  },
  {
    id: "schedule_meeting",
    label: "Schedule Calendar Meeting",
    description: "Book a meeting and distribute invites automatically.",
    category: "scheduling",
    icon: "CalendarClock",
    estimatedDurationMs: 700,
    params: [
      {
        key: "title",
        label: "Meeting Title",
        type: "text",
        required: true,
        placeholder: "Orientation - Day 1",
      },
      {
        key: "duration_mins",
        label: "Duration (minutes)",
        type: "number",
        required: true,
        placeholder: "60",
      },
      {
        key: "attendees",
        label: "Attendees",
        type: "text",
        required: false,
        placeholder: "manager@co.com, hr@co.com",
      },
      {
        key: "location",
        label: "Location or Link",
        type: "text",
        required: false,
        placeholder: "https://meet.google.com/...",
      },
    ],
  },
  {
    id: "send_webhook",
    label: "Trigger Webhook",
    description: "Send a POST payload to an external endpoint.",
    category: "integration",
    icon: "Webhook",
    estimatedDurationMs: 520,
    params: [
      {
        key: "url",
        label: "Webhook URL",
        type: "url",
        required: true,
        placeholder: "https://api.service.com/hooks",
      },
      {
        key: "event_type",
        label: "Event Type",
        type: "text",
        required: true,
        placeholder: "onboarding.completed",
      },
      {
        key: "secret_header",
        label: "Authorization Header Value",
        type: "text",
        required: false,
        placeholder: "Bearer <token>",
        hint: "Do not store real secrets in the prototype.",
      },
    ],
  },
  {
    id: "set_reminder",
    label: "Schedule Reminder",
    description: "Queue a delayed reminder for a person or team.",
    category: "scheduling",
    icon: "BellRing",
    estimatedDurationMs: 320,
    params: [
      {
        key: "days",
        label: "Remind After (days)",
        type: "number",
        required: true,
        placeholder: "3",
      },
      {
        key: "recipient",
        label: "Reminder Recipient",
        type: "text",
        required: true,
        placeholder: "hr@company.com",
      },
      {
        key: "message",
        label: "Reminder Message",
        type: "textarea",
        required: true,
        placeholder: "Please check on the document submission status...",
      },
    ],
  },
  {
    id: "provision_access",
    label: "Provision System Access",
    description: "Grant role-based access to an internal tool.",
    category: "integration",
    icon: "KeyRound",
    estimatedDurationMs: 2100,
    params: [
      {
        key: "system",
        label: "Target System",
        type: "select",
        required: true,
        options: ["GitHub", "AWS", "GCP", "Jira", "Confluence", "Figma", "Notion", "Salesforce"],
      },
      {
        key: "role",
        label: "Access Role",
        type: "select",
        required: true,
        options: ["read", "write", "admin", "custom"],
      },
      {
        key: "employee_id",
        label: "Employee ID",
        type: "text",
        required: true,
        placeholder: "EMP-20240312",
      },
    ],
  },
  {
    id: "send_survey",
    label: "Send Feedback Survey",
    description: "Dispatch a survey link to capture feedback.",
    category: "communication",
    icon: "ClipboardCheck",
    estimatedDurationMs: 430,
    params: [
      {
        key: "survey_type",
        label: "Survey Type",
        type: "select",
        required: true,
        options: [
          "onboarding_feedback",
          "exit_interview",
          "performance_pulse",
          "engagement",
          "custom",
        ],
      },
      {
        key: "to",
        label: "Send To",
        type: "email",
        required: true,
        placeholder: "employee@company.com",
      },
      {
        key: "deadline_days",
        label: "Response Deadline (days)",
        type: "number",
        required: false,
        placeholder: "7",
      },
    ],
  },
];

export function getAutomationAction(actionId: string) {
  return AUTOMATION_ACTIONS.find((action) => action.id === actionId) ?? null;
}
