import { createId } from "@lib/utils";
import type { ImportedWorkflowFile, WorkflowEdge, WorkflowNode } from "@types-app/workflow.types";

function makeEdge(source: string, target: string, sourceHandle?: string): WorkflowEdge {
  return {
    id: createId("edge"),
    type: "default",
    source,
    target,
    sourceHandle: sourceHandle ?? null,
    animated: false,
    data: {},
  };
}

function makeNode(node: WorkflowNode): WorkflowNode {
  return node;
}

export const WORKFLOW_TEMPLATES: ImportedWorkflowFile[] = [
  {
    name: "Employee Onboarding",
    description: "A guided workflow for documents, approvals, provisioning, and welcome steps.",
    graph: {
      nodes: [
        makeNode({
          id: "tmpl-start",
          type: "startNode",
          position: { x: 420, y: 60 },
          data: {
            nodeType: "startNode",
            label: "New Employee Created",
            metadata: [
              { id: "meta-1", key: "department", value: "Product" },
              { id: "meta-2", key: "location", value: "Bengaluru" },
            ],
          },
        }),
        makeNode({
          id: "tmpl-task-docs",
          type: "taskNode",
          position: { x: 420, y: 220 },
          data: {
            nodeType: "taskNode",
            label: "Collect Documents",
            description: "Gather ID proof, address proof, and signed NDA.",
            assignee: "HR Operations",
            dueDate: "2026-04-30",
            priority: "high",
            customFields: [{ id: "cf-1", key: "checklist", value: "ID, PAN, Bank" }],
          },
        }),
        makeNode({
          id: "tmpl-task-it",
          type: "taskNode",
          position: { x: 420, y: 380 },
          data: {
            nodeType: "taskNode",
            label: "IT Setup Request",
            description: "Queue laptop allocation and account setup.",
            assignee: "IT Infrastructure",
            dueDate: "2026-05-01",
            priority: "critical",
            customFields: [{ id: "cf-2", key: "device_profile", value: "Engineering MacBook" }],
          },
        }),
        makeNode({
          id: "tmpl-approval",
          type: "approvalNode",
          position: { x: 420, y: 540 },
          data: {
            nodeType: "approvalNode",
            label: "HR Review",
            approverRole: "Manager",
            autoApproveThreshold: 85,
            requireAllApprovers: false,
            timeoutHours: 48,
          },
        }),
        makeNode({
          id: "tmpl-auto-mail",
          type: "automatedStepNode",
          position: { x: 420, y: 700 },
          data: {
            nodeType: "automatedStepNode",
            label: "Send Welcome Email",
            actionId: "send_email",
            actionParams: {
              to: "newhire@company.com",
              subject: "Welcome to NexusFlow",
              template: "welcome",
            },
          },
        }),
        makeNode({
          id: "tmpl-auto-ticket",
          type: "automatedStepNode",
          position: { x: 420, y: 860 },
          data: {
            nodeType: "automatedStepNode",
            label: "Create Access Ticket",
            actionId: "create_ticket",
            actionParams: {
              title: "Provision laptop and SaaS access",
              priority: "high",
              team: "IT Infrastructure",
            },
          },
        }),
        makeNode({
          id: "tmpl-end",
          type: "endNode",
          position: { x: 420, y: 1020 },
          data: {
            nodeType: "endNode",
            label: "Onboarding Ready",
            endMessage: "Employee setup is complete and ready for day one.",
            showSummary: true,
            outcomeType: "success",
          },
        }),
      ],
      edges: [
        makeEdge("tmpl-start", "tmpl-task-docs"),
        makeEdge("tmpl-task-docs", "tmpl-task-it"),
        makeEdge("tmpl-task-it", "tmpl-approval"),
        makeEdge("tmpl-approval", "tmpl-auto-mail", "approved"),
        makeEdge("tmpl-auto-mail", "tmpl-auto-ticket"),
        makeEdge("tmpl-auto-ticket", "tmpl-end"),
      ],
    },
  },
  {
    name: "Leave Approval",
    description: "Collect a leave request, route approval, and update HR data.",
    graph: {
      nodes: [
        makeNode({
          id: "leave-start",
          type: "startNode",
          position: { x: 420, y: 60 },
          data: {
            nodeType: "startNode",
            label: "Leave Requested",
            metadata: [{ id: "leave-meta-1", key: "type", value: "Annual Leave" }],
          },
        }),
        makeNode({
          id: "leave-task",
          type: "taskNode",
          position: { x: 420, y: 220 },
          data: {
            nodeType: "taskNode",
            label: "Submit Leave Request",
            description: "Confirm dates, handover notes, and backup owner.",
            assignee: "Employee",
            dueDate: "2026-05-02",
            priority: "medium",
            customFields: [{ id: "leave-cf-1", key: "backup_owner", value: "Priya" }],
          },
        }),
        makeNode({
          id: "leave-approval",
          type: "approvalNode",
          position: { x: 420, y: 380 },
          data: {
            nodeType: "approvalNode",
            label: "Manager Approval",
            approverRole: "Manager",
            autoApproveThreshold: 50,
            requireAllApprovers: false,
            timeoutHours: 24,
          },
        }),
        makeNode({
          id: "leave-hris",
          type: "automatedStepNode",
          position: { x: 420, y: 540 },
          data: {
            nodeType: "automatedStepNode",
            label: "Update HRIS Status",
            actionId: "update_hris",
            actionParams: {
              field: "employment_status",
              value: "Leave Approved",
              effective_date: "2026-05-07",
            },
          },
        }),
        makeNode({
          id: "leave-end",
          type: "endNode",
          position: { x: 420, y: 700 },
          data: {
            nodeType: "endNode",
            label: "Leave Confirmed",
            endMessage: "The leave request has been approved and recorded.",
            showSummary: true,
            outcomeType: "success",
          },
        }),
      ],
      edges: [
        makeEdge("leave-start", "leave-task"),
        makeEdge("leave-task", "leave-approval"),
        makeEdge("leave-approval", "leave-hris", "approved"),
        makeEdge("leave-hris", "leave-end"),
      ],
    },
  },
  {
    name: "Document Verification",
    description: "Review uploaded documents, generate output, and approve completion.",
    graph: {
      nodes: [
        makeNode({
          id: "doc-start",
          type: "startNode",
          position: { x: 420, y: 60 },
          data: {
            nodeType: "startNode",
            label: "Documents Received",
            metadata: [{ id: "doc-meta-1", key: "channel", value: "Portal Upload" }],
          },
        }),
        makeNode({
          id: "doc-upload",
          type: "taskNode",
          position: { x: 420, y: 220 },
          data: {
            nodeType: "taskNode",
            label: "Upload Documents",
            description: "Collect source docs and confirm completeness.",
            assignee: "Applicant",
            dueDate: "2026-05-03",
            priority: "high",
            customFields: [{ id: "doc-cf-1", key: "bundle", value: "Passport, Address Proof" }],
          },
        }),
        makeNode({
          id: "doc-generate",
          type: "automatedStepNode",
          position: { x: 420, y: 380 },
          data: {
            nodeType: "automatedStepNode",
            label: "Generate PDF",
            actionId: "generate_doc",
            actionParams: {
              template: "policy_doc",
              recipient: "Verification Packet",
              format: "pdf",
            },
          },
        }),
        makeNode({
          id: "doc-approval",
          type: "approvalNode",
          position: { x: 420, y: 540 },
          data: {
            nodeType: "approvalNode",
            label: "Director Review",
            approverRole: "Director",
            autoApproveThreshold: 92,
            requireAllApprovers: true,
            timeoutHours: 72,
          },
        }),
        makeNode({
          id: "doc-end",
          type: "endNode",
          position: { x: 420, y: 700 },
          data: {
            nodeType: "endNode",
            label: "Verification Complete",
            endMessage: "All documents were validated and archived.",
            showSummary: true,
            outcomeType: "success",
          },
        }),
      ],
      edges: [
        makeEdge("doc-start", "doc-upload"),
        makeEdge("doc-upload", "doc-generate"),
        makeEdge("doc-generate", "doc-approval"),
        makeEdge("doc-approval", "doc-end", "approved"),
      ],
    },
  },
  {
    name: "Exit Interview Process",
    description: "Coordinate exit paperwork, meeting logistics, approvals, and HR record updates.",
    graph: {
      nodes: [
        makeNode({
          id: "exit-start",
          type: "startNode",
          position: { x: 420, y: 60 },
          data: {
            nodeType: "startNode",
            label: "Offboarding Triggered",
            metadata: [{ id: "exit-meta-1", key: "reason", value: "Resignation" }],
          },
        }),
        makeNode({
          id: "exit-task",
          type: "taskNode",
          position: { x: 420, y: 220 },
          data: {
            nodeType: "taskNode",
            label: "Self Evaluation Form",
            description: "Collect feedback and returning-assets checklist.",
            assignee: "Employee",
            dueDate: "2026-05-05",
            priority: "medium",
            customFields: [{ id: "exit-cf-1", key: "asset_return", value: "Laptop, Badge" }],
          },
        }),
        makeNode({
          id: "exit-meeting",
          type: "automatedStepNode",
          position: { x: 420, y: 380 },
          data: {
            nodeType: "automatedStepNode",
            label: "Schedule Exit Meeting",
            actionId: "schedule_meeting",
            actionParams: {
              title: "Exit Interview",
              duration_mins: "45",
              attendees: "hr@company.com, manager@company.com",
              location: "Conference Room 2",
            },
          },
        }),
        makeNode({
          id: "exit-approval",
          type: "approvalNode",
          position: { x: 420, y: 540 },
          data: {
            nodeType: "approvalNode",
            label: "HR Approval",
            approverRole: "HRBP",
            autoApproveThreshold: 70,
            requireAllApprovers: false,
            timeoutHours: 24,
          },
        }),
        makeNode({
          id: "exit-update",
          type: "automatedStepNode",
          position: { x: 420, y: 700 },
          data: {
            nodeType: "automatedStepNode",
            label: "Update HRIS Record",
            actionId: "update_hris",
            actionParams: {
              field: "employment_status",
              value: "Exited",
              effective_date: "2026-05-10",
            },
          },
        }),
        makeNode({
          id: "exit-end",
          type: "endNode",
          position: { x: 420, y: 860 },
          data: {
            nodeType: "endNode",
            label: "Exit Closed",
            endMessage: "The offboarding flow has been completed and logged.",
            showSummary: true,
            outcomeType: "cancelled",
          },
        }),
      ],
      edges: [
        makeEdge("exit-start", "exit-task"),
        makeEdge("exit-task", "exit-meeting"),
        makeEdge("exit-meeting", "exit-approval"),
        makeEdge("exit-approval", "exit-update", "approved"),
        makeEdge("exit-update", "exit-end"),
      ],
    },
  },
  {
    name: "Enterprise Customer Onboarding",
    description:
      "Run sales handoff, security review, workspace setup, stakeholder notifications, and launch confirmation with fallback branches.",
    graph: {
      nodes: [
        makeNode({
          id: "cust-start",
          type: "startNode",
          position: { x: 560, y: 60 },
          data: {
            nodeType: "startNode",
            label: "Contract Signed",
            metadata: [
              { id: "cust-meta-1", key: "plan", value: "Enterprise" },
              { id: "cust-meta-2", key: "region", value: "US-East" },
            ],
          },
        }),
        makeNode({
          id: "cust-task-handoff",
          type: "taskNode",
          position: { x: 560, y: 220 },
          data: {
            nodeType: "taskNode",
            label: "Sales to CS Handoff",
            description: "Capture goals, stakeholders, integrations, and launch timeline.",
            assignee: "Customer Success",
            dueDate: "2026-05-12",
            priority: "high",
            customFields: [
              { id: "cust-cf-1", key: "go_live_target", value: "2026-05-31" },
              { id: "cust-cf-2", key: "success_owner", value: "A. Mehta" },
            ],
          },
        }),
        makeNode({
          id: "cust-doc-pack",
          type: "automatedStepNode",
          position: { x: 560, y: 380 },
          data: {
            nodeType: "automatedStepNode",
            label: "Generate Kickoff Pack",
            actionId: "generate_doc",
            actionParams: {
              template: "policy_doc",
              recipient: "Customer Kickoff Pack",
              format: "pdf",
            },
          },
        }),
        makeNode({
          id: "cust-security-task",
          type: "taskNode",
          position: { x: 560, y: 540 },
          data: {
            nodeType: "taskNode",
            label: "Collect Security Responses",
            description: "Gather SSO, data residency, DPA, and questionnaire requirements.",
            assignee: "Solutions Engineering",
            dueDate: "2026-05-14",
            priority: "critical",
            customFields: [{ id: "cust-cf-3", key: "security_tier", value: "Tier 1" }],
          },
        }),
        makeNode({
          id: "cust-security-approval",
          type: "approvalNode",
          position: { x: 560, y: 700 },
          data: {
            nodeType: "approvalNode",
            label: "Security Sign-off",
            approverRole: "Director",
            autoApproveThreshold: 88,
            requireAllApprovers: true,
            timeoutHours: 72,
          },
        }),
        makeNode({
          id: "cust-provision",
          type: "automatedStepNode",
          position: { x: 380, y: 880 },
          data: {
            nodeType: "automatedStepNode",
            label: "Provision Workspace",
            actionId: "send_webhook",
            actionParams: {
              url: "https://ops.example.com/hooks/customer-onboarding",
              event_type: "customer.workspace.provision",
              secret_header: "Bearer demo-token",
            },
          },
        }),
        makeNode({
          id: "cust-kickoff",
          type: "automatedStepNode",
          position: { x: 380, y: 1040 },
          data: {
            nodeType: "automatedStepNode",
            label: "Schedule Kickoff",
            actionId: "schedule_meeting",
            actionParams: {
              title: "Enterprise Kickoff",
              duration_mins: "60",
              attendees: "cs@company.com, sponsor@customer.com",
              location: "Zoom",
            },
          },
        }),
        makeNode({
          id: "cust-notify",
          type: "automatedStepNode",
          position: { x: 740, y: 880 },
          data: {
            nodeType: "automatedStepNode",
            label: "Notify Risk Team",
            actionId: "slack_notify",
            actionParams: {
              channel: "#security-escalations",
              message: "Enterprise onboarding blocked pending security review.",
              mention_user: "@risk-lead",
            },
          },
        }),
        makeNode({
          id: "cust-reminder",
          type: "automatedStepNode",
          position: { x: 740, y: 1040 },
          data: {
            nodeType: "automatedStepNode",
            label: "Queue Follow-up Reminder",
            actionId: "set_reminder",
            actionParams: {
              days: "2",
              recipient: "security@company.com",
              message: "Review outstanding customer security blockers.",
            },
          },
        }),
        makeNode({
          id: "cust-end-success",
          type: "endNode",
          position: { x: 380, y: 1200 },
          data: {
            nodeType: "endNode",
            label: "Customer Live",
            endMessage: "The customer workspace is provisioned and kickoff is scheduled.",
            showSummary: true,
            outcomeType: "success",
          },
        }),
        makeNode({
          id: "cust-end-risk",
          type: "endNode",
          position: { x: 740, y: 1200 },
          data: {
            nodeType: "endNode",
            label: "Awaiting Security Resolution",
            endMessage: "Security blockers were escalated and the launch remains on hold.",
            showSummary: true,
            outcomeType: "failure",
          },
        }),
      ],
      edges: [
        makeEdge("cust-start", "cust-task-handoff"),
        makeEdge("cust-task-handoff", "cust-doc-pack"),
        makeEdge("cust-doc-pack", "cust-security-task"),
        makeEdge("cust-security-task", "cust-security-approval"),
        makeEdge("cust-security-approval", "cust-provision", "approved"),
        makeEdge("cust-provision", "cust-kickoff"),
        makeEdge("cust-kickoff", "cust-end-success"),
        makeEdge("cust-security-approval", "cust-notify", "rejected"),
        makeEdge("cust-notify", "cust-reminder"),
        makeEdge("cust-reminder", "cust-end-risk"),
      ],
    },
  },
  {
    name: "Security Incident Response",
    description:
      "Coordinate triage, evidence collection, executive escalation, remediation, and postmortem communication through parallel outcomes.",
    graph: {
      nodes: [
        makeNode({
          id: "sec-start",
          type: "startNode",
          position: { x: 560, y: 60 },
          data: {
            nodeType: "startNode",
            label: "Critical Alert Triggered",
            metadata: [
              { id: "sec-meta-1", key: "severity", value: "SEV-1" },
              { id: "sec-meta-2", key: "source", value: "SIEM" },
            ],
          },
        }),
        makeNode({
          id: "sec-triage",
          type: "taskNode",
          position: { x: 560, y: 220 },
          data: {
            nodeType: "taskNode",
            label: "SOC Triage",
            description: "Validate blast radius, affected systems, and initial containment plan.",
            assignee: "Security Operations",
            dueDate: "2026-05-15",
            priority: "critical",
            customFields: [{ id: "sec-cf-1", key: "incident_id", value: "INC-240515-01" }],
          },
        }),
        makeNode({
          id: "sec-ticket",
          type: "automatedStepNode",
          position: { x: 560, y: 380 },
          data: {
            nodeType: "automatedStepNode",
            label: "Create Incident Ticket",
            actionId: "create_ticket",
            actionParams: {
              title: "SEV-1 incident response bridge",
              priority: "critical",
              team: "Security",
              due_days: "1",
            },
          },
        }),
        makeNode({
          id: "sec-approval",
          type: "approvalNode",
          position: { x: 560, y: 540 },
          data: {
            nodeType: "approvalNode",
            label: "Executive Escalation Check",
            approverRole: "VP",
            autoApproveThreshold: 90,
            requireAllApprovers: false,
            timeoutHours: 6,
          },
        }),
        makeNode({
          id: "sec-remediation",
          type: "taskNode",
          position: { x: 380, y: 720 },
          data: {
            nodeType: "taskNode",
            label: "Coordinate Remediation",
            description: "Assign fix owners, rollback plan, and recovery checkpoints.",
            assignee: "Incident Commander",
            dueDate: "2026-05-15",
            priority: "critical",
            customFields: [{ id: "sec-cf-2", key: "bridge", value: "war-room-1" }],
          },
        }),
        makeNode({
          id: "sec-update",
          type: "automatedStepNode",
          position: { x: 380, y: 880 },
          data: {
            nodeType: "automatedStepNode",
            label: "Send Stakeholder Update",
            actionId: "send_email",
            actionParams: {
              to: "leadership@company.com",
              subject: "SEV-1 incident in progress",
              template: "approval_request",
            },
          },
        }),
        makeNode({
          id: "sec-postmortem",
          type: "automatedStepNode",
          position: { x: 380, y: 1040 },
          data: {
            nodeType: "automatedStepNode",
            label: "Create Postmortem Draft",
            actionId: "generate_doc",
            actionParams: {
              template: "policy_doc",
              recipient: "Incident Postmortem",
              format: "docx",
            },
          },
        }),
        makeNode({
          id: "sec-escalate-slack",
          type: "automatedStepNode",
          position: { x: 740, y: 720 },
          data: {
            nodeType: "automatedStepNode",
            label: "Notify Executive Channel",
            actionId: "slack_notify",
            actionParams: {
              channel: "#exec-war-room",
              message: "Executive escalation requested for active SEV-1 incident.",
              mention_user: "@cto",
            },
          },
        }),
        makeNode({
          id: "sec-reminder",
          type: "automatedStepNode",
          position: { x: 740, y: 880 },
          data: {
            nodeType: "automatedStepNode",
            label: "Schedule Review Reminder",
            actionId: "set_reminder",
            actionParams: {
              days: "1",
              recipient: "security-lead@company.com",
              message: "Review exec escalation status and legal updates.",
            },
          },
        }),
        makeNode({
          id: "sec-end-contained",
          type: "endNode",
          position: { x: 380, y: 1200 },
          data: {
            nodeType: "endNode",
            label: "Incident Contained",
            endMessage: "Remediation and communication steps were completed successfully.",
            showSummary: true,
            outcomeType: "success",
          },
        }),
        makeNode({
          id: "sec-end-escalated",
          type: "endNode",
          position: { x: 740, y: 1040 },
          data: {
            nodeType: "endNode",
            label: "Escalation Active",
            endMessage: "The incident remains under executive escalation and active monitoring.",
            showSummary: true,
            outcomeType: "cancelled",
          },
        }),
      ],
      edges: [
        makeEdge("sec-start", "sec-triage"),
        makeEdge("sec-triage", "sec-ticket"),
        makeEdge("sec-ticket", "sec-approval"),
        makeEdge("sec-approval", "sec-remediation", "approved"),
        makeEdge("sec-remediation", "sec-update"),
        makeEdge("sec-update", "sec-postmortem"),
        makeEdge("sec-postmortem", "sec-end-contained"),
        makeEdge("sec-approval", "sec-escalate-slack", "rejected"),
        makeEdge("sec-escalate-slack", "sec-reminder"),
        makeEdge("sec-reminder", "sec-end-escalated"),
      ],
    },
  },
  {
    name: "Benefits Enrollment Audit",
    description:
      "Guide employees through benefits enrollment, payroll review, compliance validation, and exception handling.",
    graph: {
      nodes: [
        makeNode({
          id: "benefits-start",
          type: "startNode",
          position: { x: 560, y: 60 },
          data: {
            nodeType: "startNode",
            label: "Enrollment Window Opened",
            metadata: [
              { id: "benefits-meta-1", key: "cycle", value: "Q2 Open Enrollment" },
              { id: "benefits-meta-2", key: "market", value: "India" },
            ],
          },
        }),
        makeNode({
          id: "benefits-task",
          type: "taskNode",
          position: { x: 560, y: 220 },
          data: {
            nodeType: "taskNode",
            label: "Submit Benefit Choices",
            description: "Collect dependent coverage, nominees, and declarations.",
            assignee: "Employee",
            dueDate: "2026-05-20",
            priority: "high",
            customFields: [{ id: "benefits-cf-1", key: "coverage_level", value: "Family" }],
          },
        }),
        makeNode({
          id: "benefits-hris",
          type: "automatedStepNode",
          position: { x: 560, y: 380 },
          data: {
            nodeType: "automatedStepNode",
            label: "Sync Elections to HRIS",
            actionId: "update_hris",
            actionParams: {
              field: "benefits_plan",
              value: "Pending Validation",
              effective_date: "2026-06-01",
            },
          },
        }),
        makeNode({
          id: "benefits-approval",
          type: "approvalNode",
          position: { x: 560, y: 540 },
          data: {
            nodeType: "approvalNode",
            label: "Compliance Audit",
            approverRole: "HRBP",
            autoApproveThreshold: 80,
            requireAllApprovers: true,
            timeoutHours: 48,
          },
        }),
        makeNode({
          id: "benefits-payroll",
          type: "automatedStepNode",
          position: { x: 380, y: 720 },
          data: {
            nodeType: "automatedStepNode",
            label: "Raise Payroll Ticket",
            actionId: "create_ticket",
            actionParams: {
              title: "Update salary deductions for benefits cycle",
              priority: "high",
              team: "Finance",
              due_days: "2",
            },
          },
        }),
        makeNode({
          id: "benefits-email",
          type: "automatedStepNode",
          position: { x: 380, y: 880 },
          data: {
            nodeType: "automatedStepNode",
            label: "Send Confirmation Pack",
            actionId: "send_email",
            actionParams: {
              to: "employee@company.com",
              subject: "Benefits enrollment confirmed",
              template: "completion",
            },
          },
        }),
        makeNode({
          id: "benefits-escalate",
          type: "taskNode",
          position: { x: 740, y: 720 },
          data: {
            nodeType: "taskNode",
            label: "Resolve Enrollment Exception",
            description: "Fix missing proofs, incorrect declarations, or compliance gaps.",
            assignee: "Benefits Operations",
            dueDate: "2026-05-21",
            priority: "high",
            customFields: [
              { id: "benefits-cf-2", key: "exception_type", value: "Dependent proof" },
            ],
          },
        }),
        makeNode({
          id: "benefits-reminder",
          type: "automatedStepNode",
          position: { x: 740, y: 880 },
          data: {
            nodeType: "automatedStepNode",
            label: "Send Correction Reminder",
            actionId: "set_reminder",
            actionParams: {
              days: "1",
              recipient: "employee@company.com",
              message: "Please submit the pending benefits validation documents.",
            },
          },
        }),
        makeNode({
          id: "benefits-end-success",
          type: "endNode",
          position: { x: 380, y: 1040 },
          data: {
            nodeType: "endNode",
            label: "Enrollment Confirmed",
            endMessage: "Benefits enrollment was validated and passed to payroll successfully.",
            showSummary: true,
            outcomeType: "success",
          },
        }),
        makeNode({
          id: "benefits-end-exception",
          type: "endNode",
          position: { x: 740, y: 1040 },
          data: {
            nodeType: "endNode",
            label: "Pending Employee Correction",
            endMessage: "The enrollment needs more employee action before it can be finalized.",
            showSummary: true,
            outcomeType: "failure",
          },
        }),
      ],
      edges: [
        makeEdge("benefits-start", "benefits-task"),
        makeEdge("benefits-task", "benefits-hris"),
        makeEdge("benefits-hris", "benefits-approval"),
        makeEdge("benefits-approval", "benefits-payroll", "approved"),
        makeEdge("benefits-payroll", "benefits-email"),
        makeEdge("benefits-email", "benefits-end-success"),
        makeEdge("benefits-approval", "benefits-escalate", "rejected"),
        makeEdge("benefits-escalate", "benefits-reminder"),
        makeEdge("benefits-reminder", "benefits-end-exception"),
      ],
    },
  },
  {
    name: "Vendor Procurement Review",
    description:
      "Manage intake, legal review, infosec checks, procurement approval, and vendor activation with clear approval exits.",
    graph: {
      nodes: [
        makeNode({
          id: "vendor-start",
          type: "startNode",
          position: { x: 560, y: 60 },
          data: {
            nodeType: "startNode",
            label: "Vendor Request Submitted",
            metadata: [
              { id: "vendor-meta-1", key: "spend_band", value: "High" },
              { id: "vendor-meta-2", key: "category", value: "SaaS" },
            ],
          },
        }),
        makeNode({
          id: "vendor-intake",
          type: "taskNode",
          position: { x: 560, y: 220 },
          data: {
            nodeType: "taskNode",
            label: "Collect Vendor Intake",
            description: "Capture business owner, use case, data access, and renewal terms.",
            assignee: "Requester",
            dueDate: "2026-05-22",
            priority: "high",
            customFields: [{ id: "vendor-cf-1", key: "annual_cost", value: "180000" }],
          },
        }),
        makeNode({
          id: "vendor-legal",
          type: "taskNode",
          position: { x: 560, y: 380 },
          data: {
            nodeType: "taskNode",
            label: "Legal Redline Review",
            description: "Review MSA, DPA, security rider, and liability language.",
            assignee: "Legal",
            dueDate: "2026-05-24",
            priority: "critical",
            customFields: [{ id: "vendor-cf-2", key: "contract_type", value: "MSA + Order Form" }],
          },
        }),
        makeNode({
          id: "vendor-security",
          type: "automatedStepNode",
          position: { x: 560, y: 540 },
          data: {
            nodeType: "automatedStepNode",
            label: "Trigger Security Questionnaire",
            actionId: "send_webhook",
            actionParams: {
              url: "https://ops.example.com/hooks/vendor-security",
              event_type: "vendor.security.review",
              secret_header: "Bearer demo-token",
            },
          },
        }),
        makeNode({
          id: "vendor-approval",
          type: "approvalNode",
          position: { x: 560, y: 700 },
          data: {
            nodeType: "approvalNode",
            label: "Procurement Approval",
            approverRole: "Director",
            autoApproveThreshold: 84,
            requireAllApprovers: true,
            timeoutHours: 48,
          },
        }),
        makeNode({
          id: "vendor-activate",
          type: "automatedStepNode",
          position: { x: 380, y: 880 },
          data: {
            nodeType: "automatedStepNode",
            label: "Activate Vendor Record",
            actionId: "update_hris",
            actionParams: {
              field: "department",
              value: "Approved Vendor",
              effective_date: "2026-05-25",
            },
          },
        }),
        makeNode({
          id: "vendor-notify",
          type: "automatedStepNode",
          position: { x: 380, y: 1040 },
          data: {
            nodeType: "automatedStepNode",
            label: "Notify Requester",
            actionId: "send_email",
            actionParams: {
              to: "requester@company.com",
              subject: "Vendor approved and activated",
              template: "completion",
            },
          },
        }),
        makeNode({
          id: "vendor-rework",
          type: "taskNode",
          position: { x: 740, y: 880 },
          data: {
            nodeType: "taskNode",
            label: "Resolve Approval Gaps",
            description: "Address missing legal terms, cost controls, or security findings.",
            assignee: "Procurement Ops",
            dueDate: "2026-05-25",
            priority: "high",
            customFields: [{ id: "vendor-cf-3", key: "gap_owner", value: "Procurement Ops" }],
          },
        }),
        makeNode({
          id: "vendor-slack",
          type: "automatedStepNode",
          position: { x: 740, y: 1040 },
          data: {
            nodeType: "automatedStepNode",
            label: "Post Review Blocker",
            actionId: "slack_notify",
            actionParams: {
              channel: "#procurement-review",
              message: "Vendor request blocked pending rework and missing approvals.",
              mention_user: "@procurement-lead",
            },
          },
        }),
        makeNode({
          id: "vendor-end-approved",
          type: "endNode",
          position: { x: 380, y: 1200 },
          data: {
            nodeType: "endNode",
            label: "Vendor Approved",
            endMessage: "The vendor completed legal, security, and procurement checks.",
            showSummary: true,
            outcomeType: "success",
          },
        }),
        makeNode({
          id: "vendor-end-blocked",
          type: "endNode",
          position: { x: 740, y: 1200 },
          data: {
            nodeType: "endNode",
            label: "Vendor Blocked",
            endMessage: "The request is blocked until the identified review gaps are resolved.",
            showSummary: true,
            outcomeType: "failure",
          },
        }),
      ],
      edges: [
        makeEdge("vendor-start", "vendor-intake"),
        makeEdge("vendor-intake", "vendor-legal"),
        makeEdge("vendor-legal", "vendor-security"),
        makeEdge("vendor-security", "vendor-approval"),
        makeEdge("vendor-approval", "vendor-activate", "approved"),
        makeEdge("vendor-activate", "vendor-notify"),
        makeEdge("vendor-notify", "vendor-end-approved"),
        makeEdge("vendor-approval", "vendor-rework", "rejected"),
        makeEdge("vendor-rework", "vendor-slack"),
        makeEdge("vendor-slack", "vendor-end-blocked"),
      ],
    },
  },
];
